### ISSUE TITLE
Errors when using orderBy()

### ISSUE THREAD

**Issue by p4-k4** [vedartm/paginate_firestore#109]
When using the `orderBy()` method the following errors occur and get an infinite progress indicator on the UI.

```[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [cloud_firestore/invalid-argument] Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).
#0      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:110:7)
<asynchronous suspension>
#1      _JsonQuery.get (package:cloud_firestore/src/query.dart:390:9)
<asynchronous suspension>
#2      PaginationCubit.refreshPaginatedList (package:paginate_firestore/bloc/pagination_cubit.dart:61:29)
<asynchronous suspension>
```

However, after removing the `orderBy()` method, everything works fine. I've created index's for the collection and can confirm the respective fields exist.

This is how I'm implementing it:

```dart
class PostFeed extends StatelessWidget {
  const PostFeed(
      {required this.documentSnapshot, required this.header, Key? key})
      : super(key: key);
  final Query<Object?> documentSnapshot;
  final Widget header;

  @override
  Widget build(BuildContext context) {
    PaginateRefreshedChangeListener refreshChangeListener =
        PaginateRefreshedChangeListener();
    return RefreshIndicator(
      child: PaginateFirestore(
        header: SliverToBoxAdapter(
            child: Column(children: [header, const SizedBox(height: 150)])),
        // isLive: true,
        shrinkWrap: true,
        itemsPerPage: 3,
        query: documentSnapshot.orderBy('title'),
        listeners: [refreshChangeListener],
        itemBuilderType: PaginateBuilderType.listView,
        physics: const AlwaysScrollableScrollPhysics(),
        itemBuilder: (context, documentSnapshots, index) {
          final data = documentSnapshots[index];
          return Card(
              child: SizedBox(height: 300.9, child: Text(data.get('title'))));
        },
      ),
      onRefresh: () async => refreshChangeListener.refreshed = false,
    );
  }
}
```

Loving this package, it literally saved my ass, but this was a bit of a bummer. Any ideas?

Thanks

**Comment by p4-k4** [comment]
Apologies, operator fault here. This can be totally ignored but for those wondering - This is what happens when you stack the `orderBy()` mehtod therefore, just use one.
